variables:
  GIT_SUBMODULE_STRATEGY: recursive

ubuntu:
  stage: build
  tags: [ubuntu]
  script: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
  artifacts:
    name: $CI_PROJECT_TITLE-$CI_JOB_NAME-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    paths: [./liblpvl.so]

windows:
  stage: build
  tags: [windows]
  script:
     - mingw64-cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
