variables:
  GIT_SUBMODULE_STRATEGY: recursive

ubuntu:
  stage: build
  tags: [ubuntu]
  script: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .

windows:
  stage: build
  tags: [windows]
  script:
     - mingw64-cmake -GNinja -DCMAKE_BUILD_TYPE=Release && cmake --build .
